# ======================
# Server
# ======================
server.port=8080
spring.application.name=api-gateway

# ======================
# Spring Cloud Gateway (WebMVC) - Routes
# Nota: en WebMVC el path es spring.cloud.gateway.server.webmvc.routes[...]
# ======================

# ---- Route 0: orders ----
spring.cloud.gateway.server.webmvc.routes[0].id=java1_route
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/java1/api/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

# ---- Route 1: payments ----
spring.cloud.gateway.server.webmvc.routes[1].id=java2_route
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/java2/api/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

# ======================
# Actuator
# ======================
management.endpoints.web.exposure.include=health,info,metrics,prometheus



# ============ Eureka Client ============
# IMPORTANTE: 'defaultZone' es case-sensitive
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
