spring.application.name=demo

student.url=localhost:8081
course.url=localhost:8082
server.port=8088



spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect