apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-schedule
  namespace: east
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-schedule
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go-schedule
        tier: backend
        tierType: business
    spec:
      containers:
        - name: go-schedule
          image: albertovs/go-schedule
          imagePullPolicy: Always
          ports:
            - name: app-port
              containerPort: 8080
          resources:
            requests:
              memory: 150Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 300m
          env:
            - name: PLAYER_INITIAL_LIVES
              valueFrom:
                configMapKeyRef:
                  name: ks-configmap
                  key: property_key_01
            - name: APP_NAME
              value: go-schedule
            - name: PROFILE
              valueFrom:
                secretKeyRef:
                  name: ks-secret-east
                  key: profile
            - name: LABEL
              valueFrom:
                secretKeyRef:
                  name: ks-secret-east
                  key: label
            - name: SSH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: ks-secret-east
                  key: ssh-private-key
          volumeMounts:
            - mountPath: "/config"
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: ks-configmap
            items:
              - key: "dev.properties"
                path: "dev.properties"
---
apiVersion: v1
kind: Service
metadata:
  name: go-schedule-service-private
  labels:
    app: go-schedule
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: httpexternal
  selector:
    app: go-schedule
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-schedule-hpa
  labels:
    app: go-schedule
    tier: backend
    tierType: business
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-schedule
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 120
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 120