apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go-2
        tier: backend
        tierType: business
    spec:
      containers:
        - name: go-2
          image: IMAGE_CONTAINER_REGISTRY
          imagePullPolicy: Always
          ports:
            - name: app-port
              containerPort: 8080
          resources:
            requests:
              memory: 150Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 300m
          env:
            - name: APP_NAME
              value: go-2
            - name: PROFILE
              valueFrom:
                secretKeyRef:
                  name: ks-secret
                  key: profile
            - name: LABEL
              valueFrom:
                secretKeyRef:
                  name: ks-secret
                  key: label
            - name: SSH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: ks-secret
                  key: ssh-private-key

---
apiVersion: v1
kind: Service
metadata:
  name: go-2-service-private
  labels:
    app: go-2
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: httpexternal
  selector:
    app: go-2
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-2-hpa
  labels:
    app: go-2
    tier: backend
    tierType: business
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-2
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 120
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 120