server.port=8081
spring.application.name=demo
course.url=localhost:8082
teacher.url=localhost:8083


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
localhost:8082/api/courses


#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/spring-realm

#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/spring-realm
#spring.security.oauth2.client.registration.keycloak.provider=keycloak
#spring.security.oauth2.client.registration.keycloak.client-id=spring-client
#spring.security.oauth2.client.registration.keycloak.client-secret=spring-client-secret
#spring.security.oauth2.client.registration.keycloak.scope=openid, profile, email


spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect