apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-teacher
  namespace: west
spec:
  replicas: 1 # editar
  selector:
    matchLabels:
      app: java-teacher # editar
  strategy:
    type: Recreate # editar
  template:
    metadata:
      labels:
        app: java-teacher # editar
        tier: backend # editar
        tierType: business # editar
    spec:
      containers:
        - name: java-teacher
          image: albertovs/java-teacher # editar
          imagePullPolicy: Always # editar
          ports:
            - name: app-port
              containerPort: 8080 # editar
          resources: # editar
            requests:
              memory: 150Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 300m
          env:
            - name: APP_NAME
              value: java-teacher
            - name: PROFILE
              valueFrom:
                secretKeyRef:
                  name: ks-secret
                  key: profile
            - name: LABEL
              valueFrom:
                secretKeyRef:
                  name: ks-secret
                  key: label
            - name: SSH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: ks-secret
                  key: ssh-private-key
          volumeMounts:
            - mountPath: /usr/share/
              name: java-teacher-pv-storage
      volumes:
        - name: java-teacher-pv-storage
          persistentVolumeClaim:
            claimName: ks-java-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: java-teacher-service-private # editar
  labels:
    app: java-teacher # editar
spec:
  type: ClusterIP # editar
  ports:
    - port: 8080 # editar
      targetPort: 8080 # editar
      protocol: TCP
      name: httpexternal
  selector:
    app: java-teacher # editar
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: java-teacher-hpa
  labels:
    app: java-teacher
    tier: backend
    tierType: business
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-teacher
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 120
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 120